apiVersion: v1
kind: Service
metadata:
  name: headless-hello-world
spec:
  clusterIP: None
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      
